version: v1.0
name: Swift
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
blocks: []
